function changeImage() {
    var image = document.getElementById('myImage');
    if (image.src.match("will1")) {
        image.src = "../IMG/chihiro1.jpg";
 
    } else {
        image.src = "../IMG/mononoke2.jpg";
 
    }
}
	
function changeImage2() {
    var image = document.getElementById('myImage');
    if (image.src.match("will1")) {
        image.src = "../IMG/mononoke2.jpg";
 
    } else {
        image.src = "../IMG/chihiro1.jpg";
 
    }
}
	
