function changeImage() {
    var image = document.getElementById('myImage');
    if (image.src.match("will1")) {
        image.src = "../IMG/dragon1.jpg";
 
    } else {
        image.src = "../IMG/dragon2.jpg";
 
    }
}
	
function changeImage2() {
    var image = document.getElementById('myImage');
    if (image.src.match("will1")) {
        image.src = "../IMG/dragon2.jpg";
 
    } else {
        image.src = "../IMG/dragon1.jpg";
 
    }
}
	
